# -*- coding: utf-8 -*-
"""210henkan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zgKTCtBiD3344RhfPLd0gyEyIxFlHjDl
"""

import tkinter as tk
from tkinter import messagebox

def convert():
    try:
        input_value = entry.get()
        if conversion_type.get() == "10進数 → 2進数":
            result = bin(int(input_value))[2:]  # 10進数を2進数に変換
        elif conversion_type.get() == "2進数 → 10進数":
            result = int(input_value, 2)  # 2進数を10進数に変換
        else:
            result = "変換タイプを選択してください"
        output_label.config(text=f"結果: {result}")
    except ValueError:
        messagebox.showerror("エラー", "正しい値を入力してください")

# GUIウィンドウの設定
root = tk.Tk()
root.title("2進数・10進数変換アプリ")

# 変換タイプ選択
conversion_type = tk.StringVar(value="10進数 → 2進数")
tk.Label(root, text="変換タイプを選択してください:").pack()
tk.Radiobutton(root, text="10進数 → 2進数", variable=conversion_type, value="10進数 → 2進数").pack()
tk.Radiobutton(root, text="2進数 → 10進数", variable=conversion_type, value="2進数 → 10進数").pack()

# 入力フィールド
tk.Label(root, text="値を入力してください:").pack()
entry = tk.Entry(root)
entry.pack()

# 変換ボタン
convert_button = tk.Button(root, text="変換", command=convert)
convert_button.pack()

# 出力ラベル
output_label = tk.Label(root, text="結果: ")
output_label.pack()

# メインループ
root.mainloop()